{{/* Input to create instance using the AWS instance plugin */}}
{{/* =% instanceProvision `aws/ec2-routetable` %= */}}

{{ $user := param "user" "string" "username" | prompt "Please enter your user name:" "string" (env "USER")}}
{{ $project := param "project" "string" "project" | prompt "Project?" "string" "myproject" }}

{{ $vpcID := param "vpcID" "string" "VPC ID" | prompt "VPC ID?" "string" }}
{{ $gatewayID := param "gatewayID" "string" "Gateway ID" | prompt "Gateway ID?" "string" }}

Tags:
  infrakit.scope: {{ $project }}
  infrakit.created: {{ now | htmlDate }}
  infrakit.user: {{ $user }}

Properties:
  Tags:
    Name: {{ $project }}-public-route-via-gateway
    infrakit.user: {{ $user }}
  CreateRouteTableInput:
    VpcId : {{ $vpcID }}
  CreateRouteInputs:
    - GatewayId: {{ $gatewayID }}
      DestinationCidrBlock: "0.0.0.0/0"
